name: png_hide
description: >-
  Hide text and other content into PNG files. The passed content
  gets encoded as Base64, then compressed using the LZW algorithm.
version: 0.0.1
author: Herry <herrytco@gmail.com>
homepage: https://github.com/herrytco/
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  image: ^2.1.4

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
