name: png_hide
description: This package can be used to encode Strings into PNG images.
version: 0.0.1
author: Herry <herrytco@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  image: ^2.1.4

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
